version: 2

models:
  - name: int_appointments
    description: "Intermediate model for cleaned and type-casted appointment data, preparing for fact table."
    columns:
      - name: appointment_id
        description: "Cleaned and null-handled unique identifier for the appointment."
      - name: patient_id
        description: "Cleaned and null-handled identifier for the patient."
      - name: doctor_id
        description: "Cleaned and null-handled identifier for the doctor."
      - name: appointment_date
        description: "Date of the appointment (casted to DATE)."
      - name: appointment_time
        description: "Time of the appointment (casted to TIME)."
      - name: reason_for_visit
        description: "Cleaned reason for the visit."
      - name: status
        description: "Cleaned status of the appointment."
      - name: _dbt_updated_at
        description: "Timestamp when this record was last updated by dbt."

  - name: int_billing
    description: "Intermediate model for cleaned and type-casted billing data, preparing for fact table."
    columns:
      - name: bill_id
        description: "Cleaned and null-handled unique identifier for the bill."
      - name: patient_id
        description: "Cleaned and null-handled identifier for the patient."
      - name: treatment_id
        description: "Cleaned and null-handled identifier for the treatment."
      - name: bill_date
        description: "Date the bill was issued (casted to DATE)."
      - name: amount
        description: "Cleaned and type-casted amount of the bill."
      - name: payment_method
        description: "Cleaned payment method."
      - name: payment_status
        description: "Cleaned status of the payment."
      - name: _dbt_updated_at
        description: "Timestamp when this record was last updated by dbt."

  - name: int_doctors
    description: "Intermediate model for cleaned and prepared doctor data, feeding into dim_doctor (SCD1)."
    columns:
      - name: doctor_id
        description: "Cleaned unique identifier for the doctor"
      - name: first_name
        description: "Cleaned first name of the doctor."
      - name: last_name
        description: "Cleaned last name of the doctor."
      - name: specialization
        description: "Cleaned doctor's medical specialization."
      - name: phone_number
        description: "Cleaned contact phone number."
      - name: years_experience
        description: "Cleaned years of experience (casted to numeric)."
      - name: hospital_branch
        description: "Cleaned hospital branch."
      - name: email
        description: "Cleaned email address."
      - name: _dbt_updated_at
        description: "Timestamp when this record was last updated by dbt."

  - name: int_patients
    description: "Intermediate model for cleaned patient data, feeding into the patient SCD2 snapshot."
    columns:
      - name: patient_id
        description: "Cleaned unique identifier for the patient (natural key for snapshot)."
      - name: first_name
        description: "Cleaned first name of the patient."
      - name: last_name
        description: "Cleaned last name of the patient."
      - name: gender
        description: "Cleaned gender of the patient."
      - name: date_of_birth
        description: "Cleaned date of birth (casted to DATE)."
      - name: contact_number
        description: "Cleaned contact phone number."
      - name: address
        description: "Cleaned patient's address."
      - name: registration_date
        description: "Cleaned registration date (casted to DATE)."
      - name: insurance_provider
        description: "Cleaned insurance provider."
      - name: insurance_number
        description: "Cleaned insurance identification number."
      - name: email
        description: "Cleaned email address."
      - name: _dbt_updated_at
        description: "Timestamp when this record was last updated by dbt."

  - name: int_treatments
    description: "Intermediate model for cleaned and prepared treatment data, deriving cost range and feeding dimensions/facts."
    columns:
      - name: treatment_id
        description: "Cleaned unique identifier for the treatment (natural key)."
      - name: appointment_id
        description: "Cleaned identifier for the associated appointment."
      - name: treatment_type
        description: "Cleaned type of treatment."
      - name: treatment_description
        description: "Cleaned detailed description of the treatment."
      - name: treatment_cost
        description: "Cleaned and type-casted cost of the treatment."
      - name: treatment_date
        description: "Date the treatment was performed (casted to DATE)."
      - name: treatment_cost_range
        description: "Derived categorical cost range for the treatment."
      - name: _dbt_updated_at
        description: "Timestamp when this record was last updated by dbt."