version: 2

models:
  - name: stg_appointments
    description: "Staging model for raw appointment data directly from the source."
    columns:
      - name: appointment_id
        description: "Unique identifier for the appointment (natural key)."
      - name: patient_id
        description: "Identifier for the patient."
      - name: doctor_id
        description: "Identifier for the doctor."
      - name: appointment_date
        description: "Date of the appointment."
      - name: appointment_time
        description: "Time of the appointment."
      - name: reason_for_visit
        description: "Reason for the patient's visit."
      - name: status
        description: "Status of the appointment (e.g., 'Scheduled', 'Completed', 'Canceled')."

  - name: stg_billing
    description: "Staging model for raw billing data directly from the source."
    columns:
      - name: bill_id
        description: "Unique identifier for the bill (natural key)."
      - name: patient_id
        description: "Identifier for the patient associated with the bill."
      - name: treatment_id
        description: "Identifier for the treatment associated with the bill."
      - name: bill_date
        description: "Date the bill was issued."
      - name: amount
        description: "Original amount of the bill."
      - name: payment_method
        description: "Method used for payment."
      - name: payment_status
        description: "Status of the payment (e.g., 'Paid', 'Pending', 'Failed')."

  - name: stg_doctors
    description: "Staging model for raw doctor data directly from the source."
    columns:
      - name: doctor_id
        description: "Unique identifier for the doctor (natural key)."
      - name: first_name
        description: "First name of the doctor."
      - name: last_name
        description: "Last name of the doctor."
      - name: specialization
        description: "Doctor's medical specialization."
      - name: phone_number
        description: "Contact phone number for the doctor."
      - name: years_experience
        description: "Years of experience of the doctor."
      - name: hospital_branch
        description: "Hospital branch where the doctor practices."
      - name: email
        description: "Email address of the doctor."

  - name: stg_patients
    description: "Staging model for raw patient data directly from the source."
    columns:
      - name: patient_id
        description: "Unique identifier for the patient (natural key)."
      - name: first_name
        description: "First name of the patient."
      - name: last_name
        description: "Last name of the patient."
      - name: gender
        description: "Gender of the patient."
      - name: date_of_birth
        description: "Date of birth of the patient."
      - name: contact_number
        description: "Contact phone number for the patient."
      - name: address
        description: "Patient's address."
      - name: registration_date
        description: "Date the patient registered."
      - name: insurance_provider
        description: "Patient's insurance provider."
      - name: insurance_number
        description: "Patient's insurance identification number."
      - name: email
        description: "Email address of the patient."

  - name: stg_treatments
    description: "Staging model for raw treatment data directly from the source."
    columns:
      - name: treatment_id
        description: "Unique identifier for the treatment (natural key)."
      - name: appointment_id
        description: "Identifier for the appointment associated with the treatment."
      - name: treatment_type
        description: "Type of treatment (e.g., 'Chemotherapy')."
      - name: description
        description: "Detailed description of the treatment."
      - name: cost
        description: "Cost of the treatment."
      - name: treatment_date
        description: "Date the treatment was performed."