version: 2

models:
  - name: dim_doctor
    description: 'Dimension doctor table for doctor information (Scd type 1)'
    columns:
      - name: doctor_sk
        description: 'Surrogate key for doctors (Natural Key: doctor_id)'
        tests:
          - relationships:
              to: ref('int_doctors')
              field: doctor_sk
          - unique
          - not_null
      - name: doctor_id
        description: Natural key from source 
        tests:
          - unique
          - not_null
      - name: first_name
        description: "Doctor's first name"
        tests:
          - not_null
      - name: last_name
        description: "Doctor's last name"
        tests:
          - not_null
      - name: specialization
        description: "Doctor's medical specialization"
        tests:
          - not_null
      - name: phone_number
        description: "Doctor's phone number"
      - name: years_of_experience
        description: "Doctor's total years of experience"
      - name: hospital_branch
        description: "Hospital's branch where the doctor practices"
        tests:
          - not_null
      - name: email
        description: "Doctor's email address"
        tests:
          - is_valid_email
      - name: updated_at
        description: "Timestamp when this doctors's information was last updated"
  


  - name: dim_patient
    description: 'Dimension patient table for patient information (Scd type 2)'
    columns:
      - name: patient_sk
        description: 'Surrogate key for patients (Natural Key: patient_id)'
        tests:
          - unique
          - not_null
      - name: patient_id
        description: 'Natural key from the source'
        tests:
          - unique
          - not_null
      - name: first_name
        description: "Patient's first name"
        tests:
          - not_null
      - name: last_name
        description: "Patient's last name"
        tests:
          - not_null
      - name: gender
        description: "Gender of the patient"
        tests:
          - accepted_values:
              values: ['M', 'F']
      - name: date_of_birth
        description: "Patient's birth date"
        tests:
          - not_null
      - name: contact_number
        description: "Patient's contact number information"
        tests:
          - not_null
          - is_valid_contact_number
      - name: address
        description: "Patient's residing address"
        tests:
          - not_null
      - name: registration_date
        description: "Date of patient's registration"
        tests:
          - not_null
      - name: insurance_provider
        description: "Patient's insurance provider"
        tests:
          - not_null
      - name: is_current
        description: 'Flag indicating if it is the current version of the patient'
        tests:
          - accepted_values:
              values: ['Y', 'N']
    tests:
      - dbt_utils.expression_is_true:
          expression: effective_start_date < effective_end_date

  - name: dim_treatment_type
    description: "Dimension table for treatment types, updating in place with the latest description and cost range (SCD Type 1)."
    columns:
      - name: treatment_type_sk
        description: "Surrogate key for treatment type (natural key: treatment_type)."
        tests:
          - unique
          - not_null
      - name: treatment_type
        description: "Primary identifier for the treatment type (e.g., 'Chemotherapy')."
        tests:
          - not_null
      - name: treatment_description
        description: "The latest description associated with this treatment type."
        tests:
          - not_null
      - name: treatment_cost_range
        description: "Categorized cost range for the treatment type."
        tests:
          - not_null
      - name: _dbt_updated_at
        description: "Timestamp when this dimension record was last updated/processed by dbt."
        tests:
          - not_null

  - name: fct_appointments
    description: "Fact table for individual appointments, linked to relevant dimensions."
    columns:
      - name: appointment_sk
        description: "Composite surrogate key for the appointment fact record."
        tests:
          - unique
          - not_null
      - name: appointment_key
        description: "Surrogate key for the appointment."
        tests:
          - not_null
          - relationships:
              to: ref('int_appointments')
              field: appointment_sk
      - name: patient_key
        description: "Foreign key to dim_patient, linking to the patient's version at the time of appointment."
        tests:
          - not_null
          - relationships:
              to: ref('dim_patient')
              field: patient_sk
      - name: doctor_key
        description: "Foreign key to dim_doctor."
        tests:
          - not_null
          - relationships:
              to: ref('dim_doctor')
              field: doctor_sk
      - name: appointment_date
        description: "Date of the appointment."
        tests:
          - not_null
      - name: appointment_time
        description: "Time of the appointment."
        tests:
          - not_null
      - name: reason_for_visit
        description: "Reason for the patient's visit."
        tests:
          - not_null
      - name: status
        description: "Status of the appointment."
        tests:
          - not_null
          - accepted_values: { values: ['Scheduled', 'Completed', 'Cancelled', 'No-show', 'Unknown Status'] }

  - name: fct_billing
    description: "Fact table for billing records, linked to patients and treatments."
    columns:
      - name: bill_key
        description: "Composite surrogate key for the billing fact record."
        tests:
          - unique
          - not_null
      - name: patient_key
        description: "Foreign key to dim_patient, linking to the patient's version at the time of billing."
        tests:
          - not_null
          - relationships:
              to: ref('dim_patient')
              field: patient_sk
      - name: treatment_key
        description: "Foreign key to dim_treatment_type."
        tests:
          - not_null
          - relationships:
              to: ref('fct_treatments')
              field: treatment_type_sk
      - name: bill_date
        description: "Date the bill was issued."
        tests:
          - not_null
          - date_order: { column_start: 'bill_date', column_end: 'CURRENT_DATE()' } 
      - name: amount
        description: "Amount billed for the treatment."
        tests:
          - not_null
          - is_positive 
      - name: payment_method
        description: "Method used for payment."
        tests:
          - not_null
      - name: payment_status
        description: "Status of the payment."
        tests:
          - not_null
          - accepted_values: { values: ['Paid', 'Pending', 'Failed', 'Unknown'] }

  - name: fct_patient_activity
    description: "Aggregated fact table providing a summary of key activities for each patient's current state."
    columns:
      - name: patient_key
        description: "Foreign key to the current version of dim_patient."
        tests:
          - not_null
          - unique 
          - relationships:
              to: ref('dim_patient')
              field: patient_sk
      - name: total_appointments
        description: "Total number of appointments for the patient."
        tests:
          - not_null
          - is_positive 
      - name: total_paid
        description: "Total amount successfully paid by the patient."
        tests:
          - not_null
          - is_positive 
      - name: no_show_count
        description: "Number of 'no-show' appointments for the patient."
        tests:
          - not_null
      - name: first_appointment_date
        description: "Date of the patient's earliest appointment."
      - name: last_appointment_date
        description: "Date of the patient's latest appointment."
      - name: _dbt_updated_at
        description: "Timestamp when this aggregated fact record was last updated by dbt."
        tests:
          - not_null