version: 2

models:
  - name: dim_doctor
    description: 'Dimension doctor table for doctor information (Scd type 1)'
    columns:
      - name: doctor_sk
        description: 'Surrogate key for doctors (Natural Key: doctor_id)'
        tests:
          - relationships:
              to: ref('int_doctors')
              field: doctor_sk
          - unique
          - not_null
      - name: doctor_id
        description: Natural key from source 
        tests:
          - unique
          - not_null
      - name: first_name
        description: "Doctor's first name"
        tests:
          - not_null
      - name: last_name
        description: "Doctor's last name"
        tests:
          - not_null
      - name: specialization
        description: "Doctor's medical specialization"
        tests:
          - not_null
      - name: phone_number
        description: "Doctor's phone number"
      - name: years_of_experience
        description: "Doctor's total years of experience"
      - name: hospital_branch
        description: "Hospital's branch where the doctor practices"
        tests:
          - not_null
      - name: email
        description: "Doctor's email address"
        tests:
          - is_valid_email
      - name: updated_at
        description: "Timestamp when this doctors's information was last updated"
  


  - name: dim_patient
    description: 'Dimension patient table for patient information (Scd type 2)'
    columns:
      - name: patient_sk
        description: 'Surrogate key for patients (Natural Key: patient_id)'
        tests:
          - unique
          - not_null
      - name: patient_id
        description: 'Natural key from the source'
        tests:
          - unique
          - not_null
      - name: first_name
        description: "Patient's first name"
        tests:
          - not_null
      - name: last_name
        description: "Patient's last name"
        tests:
          - not_null
      - name: gender
        description: "Gender of the patient"
        tests:
          - accepted_values:
              values: ['M', 'F']
      - name: date_of_birth
        description: "Patient's birth date"
        tests:
          - not_null
      - name: contact_number
        description: "Patient's contact number information"
        tests:
          - not_null
          - is_valid_contact_number
      - name: address
        description: "Patient's residing address"
        tests:
          - not_null
      - name: registration_date
        description: "Date of patient's registration"
        tests:
          - not_null
      - name: insurance_provider
        description: "Patient's insurance provider"
        tests:
          - not_null
      - name: is_current
        description: 'Flag indicating if it is the current version of the patient'
        tests:
          - accepted_values:
              values: ['Y', 'N']
    tests:
      - dbt_utils.expression_is_true:
          expression: effective_start_date < effective_end_date

  - name: dim_treatment_type
    description: 'Dimension treatment type table containing treatment information'